// <auto-generated />
namespace Ng2Net.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProposalDocuments2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProposalDocuments2));
        
        string IMigrationMetadata.Id
        {
            get { return "201612150749277_ProposalDocuments2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
