// <auto-generated />
namespace Ng2Net.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProposalTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProposalTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011542403_ProposalTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
